const AtelierData = [
  {
    id: "Milo_500",
    colors: [{}],
    data: [
      {
        id: "m51",
        imdId: "bird_ogtp6p",
        imgIdBg: "bird_ogtp6p",
        theme: "Floral and Fauna",
        name: "Chirping Birds",
        price: "1099",
        capacity: "500",
        bgHex: "#272727",
      },
      {
        id: "m52",
        imdId: "Swan_hbptyt",
        imgIdBg: "Swan_hbptyt",
        theme: "Floral and Fauna",
        name: "Beauty in White",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m53",
        imdId: "Never_Give_Up_a5zle1",
        imgIdBg: "Never_Give_Up_a5zle1",
        theme: "Sporty",
        name: "Never Give up",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m54",
        imdId: "sports_rry0t0",
        imgIdBg: "sports_rry0t0",
        theme: "Sporty",
        name: "Sports Fanatic",
        price: "1099",
        capacity: "500",
        bgHex: "#bcd4ed",
      },

      {
        id: "m55",
        imdId: "no_excuses_vvvgtq",
        imgIdBg: "no_excuses_vvvgtq",
        theme: "Sporty",
        name: "No Excuse",
        price: "1099",
        capacity: "500",
        bgHex: "#272727",
      },

      {
        id: "m56",
        imdId: "coffee_with_friend_jhgi0i",
        imgIdBg: "coffee_with_friend_jhgi0i",
        theme: "Best Buddies",
        name: "Cup of JoY",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m57",
        imdId: "BAKLOL_jhqz3e",
        imgIdBg: "BAKLOL_jhqz3e",
        theme: "Best Buddies",
        name: "Baklol gang",
        price: "1099",
        capacity: "500",
        bgHex: "#bcd4ed",
      },

      {
        id: "m58",
        imdId: "back_to_school_ktocde",
        imgIdBg: "back_to_school_ktocde",
        theme: "Just Kidding",
        name: "Back To School",
        price: "1099",
        capacity: "500",
        bgHex: "#ebc1cd",
      },

      {
        id: "m59",
        imdId: "bear_song_unh1tq",
        imgIdBg: "bear_song_unh1tq",
        theme: "Just Kidding",
        name: "Crazy Beats",
        price: "1099",
        capacity: "500",
        bgHex: "#a2d2ff",
      },

      {
        id: "m510",
        imdId: "unicorns_s4fqgu",
        imgIdBg: "unicorns_s4fqgu",
        theme: "Just Kidding",
        name: "Izzy Moonbow",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m511",
        imdId: "UnicornCLASH_fy9cdh",
        imgIdBg: "UnicornCLASH_fy9cdh",
        theme: "Just Kidding",
        name: "Unicorn",
        price: "1099",
        capacity: "500",
        bgHex: "#ebc1cd",
      },

      {
        id: "m512",
        imdId: "milo_stationary_tm4h43",
        imgIdBg: "milo_stationary_tm4h43",
        theme: "Just Kidding",
        name: "Draw Your Imagination",
        price: "1099",
        capacity: "500",
        bgHex: "#bcd4ed",
      },

      {
        id: "m513",
        imdId: "unicorn_riding_wwniha",
        imgIdBg: "unicorn_riding_wwniha",
        theme: "Just Kidding",
        name: "Purple Scooter",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m514",
        imdId: "music_vkhnjl",
        imgIdBg: "music_vkhnjl",
        theme: "Magical Art",
        name: "Art Is Free",
        price: "1099",
        capacity: "500",
        bgHex: "#a2d2ff",
      },

      {
        id: "m515",
        imdId: "peacock_fh1ot4",
        imgIdBg: "peacock_fh1ot4",
        theme: "Magical Art",
        name: "Peacock",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m516",
        imdId: "valentine_glass_rq71u9",
        imgIdBg: "valentine_glass_rq71u9",
        theme: "Magical Art",
        name: "Lovey-Dovey",
        price: "1099",
        capacity: "500",
        bgHex: "#bcd4ed",
      },

      {
        id: "m517",
        imdId: "peace_j8dspy",
        imgIdBg: "peace_j8dspy",
        theme: "Nirvana",
        name: "Balanced Life",
        price: "1099",
        capacity: "500",
        bgHex: "#ebc1cd",
      },

      {
        id: "m518",
        imdId: "know_YOURSELF_ph8iik",
        imgIdBg: "know_YOURSELF_ph8iik",
        theme: "Nirvana",
        name: "Know Yourself",
        price: "1099",
        capacity: "500",
        bgHex: "#a2d2ff",
      },

      {
        id: "m519",
        imdId: "improve_life_quotes_auuyjx",
        imgIdBg: "improve_life_quotes_auuyjx",
        theme: "Nirvana",
        name: "Build Good Habits",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m520",
        imdId: "happy_mind_ge4mkq",
        imgIdBg: "happy_mind_ge4mkq",
        theme: "Nirvana",
        name: "Happy Mind Happy Life",
        price: "1099",
        capacity: "500",
        bgHex: "#bcd4ed",
      },

      {
        id: "m521",
        imdId: "chase_dream_euknms",
        imgIdBg: "chase_dream_euknms",
        theme: "Teen",
        name: "Chase Your Dreams",
        price: "1099",
        capacity: "500",
        bgHex: "#ebc1cd",
      },

      {
        id: "m522",
        imdId: "SCHOOL_ar03hd",
        imgIdBg: "SCHOOL_ar03hd",
        theme: "Teen",
        name: "College Life",
        price: "1099",
        capacity: "500",
        bgHex: "#b7efc5",
      },

      {
        id: "m523",
        imdId: "own_world_bfw2iu",
        imgIdBg: "own_world_bfw2iu",
        theme: "Teen",
        name: "Create your World",
        price: "1099",
        capacity: "500",
        bgHex: "#ebc1cd",
      },

      {
        id: "m524",
        imdId: "perfect_mobarv",
        imgIdBg: "perfect_mobarv",
        theme: "Teen",
        name: "You're Perfect",
        price: "1099",
        capacity: "500",
        bgHex: "#a2d2ff",
      },

      {
        id: "m525",
        imdId: "see_world_jmo1ki",
        imgIdBg: "see_world_jmo1ki",
        theme: "Teen",
        name: "Explore the world",
        price: "1099",
        capacity: "500",
        bgHex: "#bcd4ed",
      },

      {
        id: "m526",
        imdId: "WORLD_MAP_c9wyzl",
        imgIdBg: "WORLD_MAP_c9wyzl",
        theme: "Limited Edition",
        name: "Wanderlust",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m527",
        imdId: "LADY_BOSS_lzlnfm",
        imgIdBg: "LADY_BOSS_lzlnfm",
        theme: "Limited Edition",
        name: "Boss Lady",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m528",
        imdId: "radha_kishan_tpmk6v",
        imgIdBg: "radha_kishan_tpmk6v",
        theme: "Limited Edition",
        name: "Raslila",
        price: "1099",
        capacity: "500",
        bgHex: "#ebc1cd",
      },
      {
        id: "m529",
        imdId: "army_qo6u4i",
        imgIdBg: "army_qo6u4i",
        theme: "Limited Edition",
        name: "Dil Maange More",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },
    ],
  },
];

export default AtelierData;
