const AtelierData = [
  {
    id: "Milo_500",
    colors: [{}],
    data: [
      {
        id: "m51",
        imdId: "bird_flmymt",
        imgIdBg: "bird_copy_ivilzt",
        theme: "Floral and Fauna",
        name: "Chirping Birds",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },
      {
        id: "m52",
        imdId: "Swan_x2if4a",
        imgIdBg: "Swan_mgtvr0",
        theme: "Floral and Fauna",
        name: "Beauty in White",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m53",
        imdId: "Never_Give_Up_h6bnjs",
        imgIdBg: "Never_Give_UP_ywcdtp",
        theme: "Sporty",
        name: "Never Give up",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m54",
        imdId: "sports_d0gzkt",
        imgIdBg: "sports_uq0cbd",
        theme: "Sporty",
        name: "Sports Fanatic",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m55",
        imdId: "no_excuses_qmevwg",
        imgIdBg: "no_excuses_new_gtacjw",
        theme: "Sporty",
        name: "No Excuse",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m56",
        imdId: "coffee_with_friend_xxzs0x",
        imgIdBg: "coffee_with_friend_re_sogp6n",
        theme: "Best Buddies",
        name: "Cup of JoY",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m57",
        imdId: "BAKLOL_bddy4a",
        imgIdBg: "BAKLOL_ytavri",
        theme: "Best Buddies",
        name: "Baklol gang",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m58",
        imdId: "back_to_school_msddck",
        imgIdBg: "back_to_school_copy_chmup8",
        theme: "Just Kidding",
        name: "Back To School",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m59",
        imdId: "bear_song_xarkde",
        imgIdBg: "bear_song_WCV_15-02-23_acxsw7",
        theme: "Just Kidding",
        name: "Crazy Beats",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m510",
        imdId: "unicorns_frymax",
        imgIdBg: "unicorns_rhv3o5",
        theme: "Just Kidding",
        name: "Izzy Moonbow",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m511",
        imdId: "UnicornCLASH_jxd6yh",
        imgIdBg: "UnicornCLASH_zkgdg1",
        theme: "Just Kidding",
        name: "Unicorn",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m512",
        imdId: "milo_stationary_nazke1",
        imgIdBg: "milo_stationary_copy_jyo5ru",
        theme: "Just Kidding",
        name: "Draw Your Imagination",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m513",
        imdId: "unicorn_riding_pdxhit",
        imgIdBg: "unicorn_riding_gxdvzr",
        theme: "Just Kidding",
        name: "Purple Scooter",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m514",
        imdId: "music_pwcpiv",
        imgIdBg: "music_w5ojya",
        theme: "Magical Art",
        name: "Art Is Free",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m515",
        imdId: "peacock_y7nczc",
        imgIdBg: "peacock_bqevov",
        theme: "Magical Art",
        name: "Peacock",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m516",
        imdId: "valentine_glass_cbf6pq",
        imgIdBg: "valentine_glass_rvnuia",
        theme: "Magical Art",
        name: "Lovey-Dovey",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m517",
        imdId: "peace_cmqdvb",
        imgIdBg: "peace_gk9qg6",
        theme: "Nirvana",
        name: "Balanced Life",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m518",
        imdId: "know_YOURSELF_nlbbmc",
        imgIdBg: "know_YOURSELF_bglpzb",
        theme: "Nirvana",
        name: "Know Yourself",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m519",
        imdId: "improve_life_quotes_tph2x3",
        imgIdBg: "improve_life_quotes_u9kbhm",
        theme: "Nirvana",
        name: "Build Good Habits",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m520",
        imdId: "happy_mind_ptu1mw",
        imgIdBg: "happy_mind_cw5gpi",
        theme: "Nirvana",
        name: "Happy Mind Happy Life",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m521",
        imdId: "chase_dream_lrrwtq",
        imgIdBg: "chase_dream_re_y079ln",
        theme: "Teen",
        name: "Chase Your Dreams",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m522",
        imdId: "SCHOOL_hhcd4p",
        imgIdBg: "SCHOOL_y0p4hq",
        theme: "Teen",
        name: "College Life",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m523",
        imdId: "own_world_c9v7tm",
        imgIdBg: "own_world_hinsya",
        theme: "Teen",
        name: "Create your World",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m524",
        imdId: "perfect_mmi9nk",
        imgIdBg: "perfect_boprll",
        theme: "Teen",
        name: "You're Perfect",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m525",
        imdId: "see_world_xsj53j",
        imgIdBg: "see_world_zphqtu",
        theme: "Teen",
        name: "Explore the world",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m526",
        imdId: "WORLD_MAP_lpuqpp",
        imgIdBg: "WORLD_MAP_gqrl5l",
        theme: "Limited Edition",
        name: "Wanderlust",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m527",
        imdId: "LADY_BOSS_sdtavd",
        imgIdBg: "LADY_BOSS_sdhsf4",
        theme: "Limited Edition",
        name: "Boss Lady",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },

      {
        id: "m528",
        imdId: "radha_kishan_px0uid",
        imgIdBg: "radha_kishan_uxmbvg",
        theme: "Limited Edition",
        name: "Raslila",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },
      {
        id: "m529",
        imdId: "army_ir6kpm",
        imgIdBg: "army_copy_ctbiqu",
        theme: "Limited Edition",
        name: "Dil Maange More",
        price: "1099",
        capacity: "500",
        bgHex: "",
      },
    ],
  },
];

export default AtelierData;
